from enum import IntEnum
from os import environ

RIXHUB_IP = environ.get("RIX_RIXHUB_IP", environ.get("RIX_DEFAULT_IP", "127.0.0.1"))
RIXHUB_PORT = 48104
DEFAULT_IP = environ.get("RIX_DEFAULT_IP", "127.0.0.1")


class OPCODE(IntEnum):
    STATUS_RESPONSE = 0
    PING = 1

    NODE_REGISTER = 80
    SUB_REGISTER = 81
    PUB_REGISTER = 82
    SRV_REGISTER = 83
    ACT_REGISTER = 84

    SUB_NOTIFY = 90

    NODE_DEREGISTER = 100
    SUB_DEREGISTER = 101
    PUB_DEREGISTER = 102
    SRV_DEREGISTER = 103
    ACT_DEREGISTER = 104

    PUB_MESSAGE = 120
    SRV_REQUEST_MESSAGE = 121
    SRV_RESPONSE_MESSAGE = 122
    ACT_GOAL_MESSAGE = 123
    ACT_PREEMPT_MESSAGE = 124
    ACT_CANCEL_MESSAGE = 125
    ACT_RESPONSE_MESSAGE = 126
    ACT_FEEDBACK_MESSAGE = 127
    ACT_RESULT_MESSAGE = 128

    SRV_REQUEST = 140
    ACT_REQUEST = 141
    PARAM_SET_REQUEST = 142
    PARAM_GET_REQUEST = 143
    SYSTEM_GET_REQUEST = 144

    SRV_RESPONSE = 160
    ACT_RESPONSE = 161
    PARAM_GET_RESPONSE = 162
    SYSTEM_GET_RESPONSE = 163
