import sys
import os

# This is necessary for using dynamically loaded message types due to PyInstaller limitations
rix_path = os.path.expanduser("~/.rix/python/rix")
sys.path.append(rix_path)

from typing import Any
import json
import jsonschema
from jsonmacros import JsonMacroProcessor, JsonMergeStrategy
import argparse
from urdf_converter import URDFConverter


HOME = os.path.expanduser("~")
USAGE = """jrdf [-h] function [arg]

Functions:
  create <model directory>                         - Create a JRDF model
  install <model directory>                        - Install a JRDF model
  uninstall <name>                                 - Uninstall a JRDF model
  convert <urdf file> [asset directory]            - Convert a URDF to JRDF
  list                                             - List all JRDF models
  validate <input.json>                            - Validate a JRDF JSON file
  visualize <name>                                 - Visualize a JRDF model
"""


def create(model_dir: str) -> None:
    # Get the absolute path of the model directory
    model_dir = os.path.abspath(model_dir)

    # Create the model directory if it doesn't exist
    if not os.path.isdir(model_dir):
        os.makedirs(model_dir, exist_ok=True)
        print(f"Created model directory '{model_dir}'")
    else:
        print(f"Model directory '{model_dir}' already exists.")

    # Create the assets directory if it doesn't exist
    assets_dir = os.path.join(model_dir, "assets")
    if not os.path.isdir(assets_dir):
        os.makedirs(assets_dir, exist_ok=True)
        print(f"Created assets directory '{assets_dir}'")
    else:
        print(f"Assets directory '{assets_dir}' already exists.")

    # Create a default JRDF file if it doesn't exist
    jrdf_file = os.path.join(model_dir, os.path.basename(model_dir) + ".json")
    if not os.path.isfile(jrdf_file):
        default_jrdf = {
            "$comment": "This is a default JRDF file. Edit it to define your robot model.",
            "$include": [],
            "$macros": [],
            "name": os.path.basename(model_dir),
            "links": [],
            "joints": [],
        }
        with open(jrdf_file, "w") as f:
            json.dump(default_jrdf, f, indent=4)
        print(f"Created default JRDF file '{jrdf_file}'")
    else:
        print(f"JRDF file '{jrdf_file}' already exists.")


def install(model_dir: str) -> None:
    # Get the absolute path of the model directory
    model_dir = os.path.abspath(model_dir)

    # Install the model by creating a symlink in the ~/.rix/jrdf/models directory
    if not os.path.isdir(model_dir):
        print(f"Error! Model directory '{model_dir}' does not exist.")
        return

    jrdf_file = os.path.join(model_dir, "model.json")
    # Find all .json files in model_dir
    json_files = [
        f for f in os.listdir(model_dir) if f.endswith(".json") and f != "model.json"
    ]
    if len(json_files) == 0:
        print(f"Error! No JRDF file found in '{model_dir}'.")

    try:
        processor = JsonMacroProcessor(
            merge_strategy=JsonMergeStrategy.MERGE_WITH_ERROR
        )
        for json_file in json_files:
            processor.process_file(os.path.join(model_dir, json_file))
    except Exception as e:
        print(f"Error processing JSON macros in '{model_dir}': {e}")
        return

    properties: dict[str, Any] = {}
    properties["$comment"] = (
        "This file was generated by jrdf from jsonmacros. Do not edit directly."
    )
    properties.update(processor.properties)
    with open(jrdf_file, "w") as f:
        json.dump(properties, f, indent=4)
    print(f"Created JRDF file '{jrdf_file}' from macros.")

    model_name: str
    dest_dir: str
    try:
        with open(jrdf_file, "r") as f:
            jrdf = json.load(f)
        schema = {}
        schema_file = os.path.join(HOME, ".rix", "jrdf", "jrdf_schema.json")
        with open(schema_file, "r") as f:
            schema = json.load(f)
        jsonschema.validate(instance=jrdf, schema=schema)
        model_name = jrdf["name"]
        models_dir = os.path.join(HOME, ".rix", "jrdf", "models")
        if not os.path.isdir(models_dir):
            os.makedirs(models_dir, exist_ok=True)

        dest_dir = os.path.join(models_dir, model_name)
        if os.path.islink(dest_dir) or os.path.isdir(dest_dir):
            print(f"Model '{model_name}' is already installed.")
            return
    except Exception as e:
        print(f"Error! JRDF file '{jrdf_file}' is not valid: {e}")
        return

    os.symlink(os.path.abspath(model_dir), dest_dir)
    print(f"Installed model '{model_name}'.")


def uninstall(name: str) -> None:
    models_dir = os.path.join(HOME, ".rix", "jrdf", "models")
    dest_dir = os.path.join(models_dir, name)
    if not os.path.islink(dest_dir) and not os.path.isdir(dest_dir):
        print(f"Model '{name}' is not installed.")
        return

    if os.path.islink(dest_dir):
        os.unlink(dest_dir)
    else:
        os.system(f"rm -r {dest_dir}")
    print(f"Uninstalled model '{name}'.")


def list() -> None:
    models_dir = os.path.join(HOME, ".rix", "jrdf", "models")
    if not os.path.isdir(models_dir):
        print("No JRDF models found.")
        return

    model_names = [
        name
        for name in os.listdir(models_dir)
        if os.path.isdir(os.path.join(models_dir, name))
    ]

    if not model_names:
        print("No JRDF models found.")
        return

    for name in model_names:
        print(name)


def convert(urdf_path: str, asset_dir: str | None) -> None:
    if not os.path.isfile(urdf_path):
        print(f"Error! URDF file '{urdf_path}' does not exist.")
        return

    if asset_dir and not os.path.isdir(asset_dir):
        print(f"Error! Asset directory '{asset_dir}' does not exist.")
        return

    converter = URDFConverter()
    try:
        jrdf, assets = converter.convert(urdf_path, asset_dir)

        # Create output directory ./<name> if it doesn't exist
        name = jrdf["name"].lower()
        output_dir = os.path.join(".", name)
        os.makedirs(output_dir, exist_ok=True)
        output_file = os.path.join(output_dir, name + ".json")
        with open(output_file, "w") as f:
            json.dump(jrdf, f, indent=4)

        # Validate the generated JRDF
        schema = {}
        schema_file = os.path.join(HOME, ".rix", "jrdf", "jrdf_schema.json")
        with open(schema_file, "r") as f:
            schema = json.load(f)
        jsonschema.validate(instance=jrdf, schema=schema)
        print(f"Converted URDF to JRDF and saved to '{output_file}'")

        # Copy assets if any
        if assets and asset_dir:
            dest_dir = os.path.join(output_dir, "assets")
            os.makedirs(dest_dir, exist_ok=True)
            os.system(f"cp -r {asset_dir}/* {dest_dir}/")

    except Exception as e:
        print(f"Error converting URDF to JRDF: {e}")


def validate(jrdf_file: str) -> None:
    try:
        with open(jrdf_file, "r") as f:
            jrdf = json.load(f)

        schema = {}
        schema_file = os.path.join(HOME, ".rix", "jrdf", "jrdf_schema.json")
        with open(schema_file, "r") as f:
            schema = json.load(f)

        jsonschema.validate(instance=jrdf, schema=schema)
        print(f"JRDF file '{jrdf_file}' is valid.")
    except jsonschema.ValidationError as e:
        print(f"Error validating JRDF file '{jrdf_file}': {e}")


def visualize(name: str) -> None:
    from open3d_util import Open3DRobotModel
    import open3d as o3d

    try:
        print(f"Visualizing JRDF model '{name}'...")
        
        # Create the robot model
        o3d_robot = Open3DRobotModel(name, use_modern_visualizer=True)
        
        # Get all geometries
        geometries = o3d_robot.get_all_geometries()
        
        if not geometries:
            print("No geometries found to visualize")
            return
            
        print(f"Loaded {len(geometries)} geometry objects")
        
        # Try modern visualization first (better texture support)
        try:
            visualize_modern(geometries, name)
        except Exception as e:
            print(f"Modern visualizer failed ({e}), falling back to legacy...")
            visualize_legacy(geometries, name)

    except Exception as e:
        print(f"Error visualizing JRDF model '{name}': {e}")

def visualize_modern(geometries, name: str) -> None:
    """Modern Open3D visualization with enhanced texture support"""
    import open3d as o3d
    
    try:
        # Filter out invalid geometries to prevent warnings
        valid_geometries = []
        for geom in geometries:
            if isinstance(geom, o3d.geometry.TriangleMesh):
                if not geom.is_empty() and len(geom.vertices) > 0 and len(geom.triangles) > 0:
                    valid_geometries.append(geom)
                else:
                    print(f"Skipping empty triangle mesh")
            elif isinstance(geom, o3d.geometry.LineSet):
                if len(geom.points) > 0 and len(geom.lines) > 0:
                    valid_geometries.append(geom)
                else:
                    print(f"Skipping empty line set")
            else:
                # Include other geometry types if they exist
                valid_geometries.append(geom)
        
        if not valid_geometries:
            print("No valid geometries to visualize")
            return
            
        print(f"Visualizing {len(valid_geometries)} valid geometries")
        
        # Use Open3D's draw_geometries function with enhanced settings
        o3d.visualization.draw_geometries(
            valid_geometries,
            window_name=f"JRDF Visualizer - {name}",
            width=1024,
            height=768,
            left=50,
            top=50
        )
    except Exception as e:
        raise Exception(f"Modern visualization failed: {e}")

def visualize_legacy(geometries, name: str) -> None:
    """Legacy Open3D visualization with validation"""
    import open3d as o3d
    
    try:
        # Filter out invalid geometries
        valid_geometries = []
        for geom in geometries:
            if isinstance(geom, o3d.geometry.TriangleMesh):
                if not geom.is_empty() and len(geom.vertices) > 0 and len(geom.triangles) > 0:
                    valid_geometries.append(geom)
                else:
                    print(f"Skipping empty triangle mesh in legacy visualization")
            elif isinstance(geom, o3d.geometry.LineSet):
                if len(geom.points) > 0 and len(geom.lines) > 0:
                    valid_geometries.append(geom)
                else:
                    print(f"Skipping empty line set in legacy visualization")
            else:
                valid_geometries.append(geom)
        
        if not valid_geometries:
            print("No valid geometries to visualize")
            return
            
        print(f"Using legacy visualizer for {len(valid_geometries)} valid geometries")
        
        # Create legacy visualizer
        vis = o3d.visualization.Visualizer()
        vis.create_window(window_name=f"JRDF Visualizer - {name}", width=1024, height=768)
        
        # Add geometries
        for geom in valid_geometries:
            vis.add_geometry(geom)
        
        # Configure view
        ctr = vis.get_view_control()
        ctr.set_zoom(0.8)
        
        # Run visualization
        vis.run()
        vis.destroy_window()
    except Exception as e:
        print(f"Visualization error: {e}")
        print("Please ensure Open3D is properly installed with GUI support.")


def main(args: argparse.Namespace) -> None:
    function = args.function

    if function == "create":
        if len(args.args) < 1:
            print("Error! 'create' requires at least 1 argument: <model directory>")
            return
        model_dir = args.args[0]
        create(model_dir)
        return

    if function == "install":
        if len(args.args) < 1:
            print("Error! 'install' requires at least 1 argument: <model directory>")
            return
        model_dir = args.args[0]
        install(model_dir)
        return

    if function == "uninstall":
        if len(args.args) < 1:
            print("Error! 'uninstall' requires at least 1 argument: <name>")
            return
        name = args.args[0]
        uninstall(name)
        return

    if function == "convert":
        if len(args.args) < 1:
            print("Error! 'convert' requires at least 1 argument: <urdf file>")
            return
        urdf_file = args.args[0]
        if not urdf_file:
            print("Error! 'convert' requires an input URDF file as an argument.")
            return

        asset_dir = args.args[1] if len(args.args) > 1 else None
        convert(urdf_file, asset_dir)
        return

    if function == "list":
        list()
        return

    if function == "validate":
        jrdf_file = args.args[0] if len(args.args) > 0 else None
        if not jrdf_file:
            print("Error! 'validate' requires an input JRDF file as an argument.")
            return
        validate(jrdf_file)
        return

    if function == "visualize":
        name = args.args[0] if len(args.args) > 0 else None
        if not name:
            print("Error! 'visualize' requires an input JRDF file as an argument.")
            return
        visualize(name)
        return

    print("Error! Unknown function:", function)
    print(USAGE)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="jrdf CLI", usage=USAGE)
    parser.add_argument("-v", "--version", action="version", version="jrdf 1.0")
    parser.add_argument("function", type=str, help="Function to call (convert, mesh)")
    parser.add_argument("args", type=str, nargs="*", help="Arguments for the function")
    args = parser.parse_args()
    main(args)
