from enum import IntEnum

RIX_HUB_PORT = 48104
MACHINE_ID_FILE = "~/.rix/machine_id"

class OPCODE(IntEnum):
    NODE_REGISTER = 80
    SUB_REGISTER = 81
    PUB_REGISTER = 82
    SRV_REGISTER = 83
    ACT_REGISTER = 84
    SUB_NOTIFY = 90
    PUB_NOTIFY = 91
    NODE_DEREGISTER = 100
    SUB_DEREGISTER = 101
    PUB_DEREGISTER = 102
    SRV_DEREGISTER = 103
    ACT_DEREGISTER = 104
    SRV_REQUEST = 140
    ACT_REQUEST = 141
    SRV_RESPONSE = 150
    ACT_RESPONSE = 151
    TERMINATE = 160

class ERROR_CODE(IntEnum):
    NO_ERROR = 0
    UNKNOWN_NODE_ID = 1
    DUPLICATE_NODE_ID = 2
    DUPLICATE_SUB_ID = 3
    DUPLICATE_PUB_ID = 4
    UNKNOWN_SRV = 5
    DUPLICATE_SRV_NAME = 6
    UNKNOWN_ACT = 7
    DUPLICATE_ACT_NAME = 8
    INVALID_MESSAGE_HASH = 9
    PROTOCOL_MISMATCH = 10

class PROTOCOL(IntEnum):
    TCP = 0x01
    UDP = 0x02
    SHM = 0x04
    WEB = 0x08
    WEB2 = 0x10

class TYPE(IntEnum):
    PUBLISHER = 0
    SUBSCRIBER = 1
    SERVICE = 2
    ACTION = 3